-- MySQL Script generated by MySQL Workbench
-- Wed Jun 12 19:21:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema todo_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema todo_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todo_schema` DEFAULT CHARACTER SET utf8 ;
USE `todo_schema` ;

-- -----------------------------------------------------
-- Table `todo_schema`.`status_todo_tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo_schema`.`status_todo_tasks` ;

CREATE TABLE IF NOT EXISTS `todo_schema`.`status_todo_tasks` (
  `idstatus_todo_tasks` TINYINT(1) NOT NULL,
  `name_status_todo_tasks` VARCHAR(45) NULL,
  PRIMARY KEY (`idstatus_todo_tasks`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo_schema`.`todo_tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo_schema`.`todo_tasks` ;

CREATE TABLE IF NOT EXISTS `todo_schema`.`todo_tasks` (
  `id_todo_tasks` INT NOT NULL AUTO_INCREMENT,
  `name_todo_task` VARCHAR(90) NOT NULL,
  `desc_todo_task` VARCHAR(300) NULL,
  `due_to_todo_tasks` DATETIME NULL,
  `status_todo_tasks` TINYINT(1) NULL,
  PRIMARY KEY (`id_todo_tasks`),
  INDEX `fk_status_todo_tasks_idx` (`status_todo_tasks` ASC) VISIBLE,
  CONSTRAINT `fk_status_todo_tasks`
    FOREIGN KEY (`status_todo_tasks`)
    REFERENCES `todo_schema`.`status_todo_tasks` (`idstatus_todo_tasks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo_schema`.`logs_todo_tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo_schema`.`logs_todo_tasks` ;

CREATE TABLE IF NOT EXISTS `todo_schema`.`logs_todo_tasks` (
  `idlogs_todo_tasks` INT NOT NULL,
  `todo_tasks_id_todo_tasks` INT NOT NULL,
  PRIMARY KEY (`idlogs_todo_tasks`),
  INDEX `dk_id_todo_tasks_idx` (`todo_tasks_id_todo_tasks` ASC) VISIBLE,
  CONSTRAINT `fk_id_todo_tasks`
    FOREIGN KEY (`todo_tasks_id_todo_tasks`)
    REFERENCES `todo_schema`.`todo_tasks` (`id_todo_tasks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
